#pragma once

#define Gen1StartAuto_ADR 1
#define Gen1StopAuto_ADR 2
#define Gen1Running_ADR 3
#define Gen1stopped_ADR 4
#define Gen1Local_ADR 5
#define Gen1Auto_ADR 6
#define Gen1Failure_ADR 7
#define Gen1RefPower_ADR 0
#define Gen1ActPower_ADR 1
#define Gen1ActRPM_ADR 2
#define Gen2StartAuto_ADR 8
#define Gen2StopAuto_ADR 9
#define Gen2Running_ADR 10
#define Gen2stopped_ADR 11
#define Gen2Local_ADR 12
#define Gen2Auto_ADR 13
#define Gen2Failure_ADR 14
#define Gen2RefPower_ADR 3
#define Gen2ActPower_ADR 4
#define Gen2ActRPM_ADR 5
#define Brkr1CmdClsAut_ADR 15
#define Brkr1CmdOpAut_ADR 16
#define Brkr1Closed_ADR 17
#define Brkr1Opened_ADR 18
#define Brkr1Local_ADR 19
#define Brkr1Auto_ADR 20
#define Brkr1Failure_ADR 21
#define Brkr2CmdClsAut_ADR 22
#define Brkr2CmdOpAut_ADR 23
#define Brkr2Closed_ADR 24
#define Brkr2Opened_ADR 25
#define Brkr2Local_ADR 26
#define Brkr2Auto_ADR 27
#define Brkr2Failure_ADR 28
#define Brkr3CmdClsAut_ADR 29
#define Brkr3CmdOpAut_ADR 30
#define Brkr3Closed_ADR 31
#define Brkr3Opened_ADR 32
#define Brkr3Local_ADR 33
#define Brkr3Auto_ADR 34
#define Brkr3Failure_ADR 35
#define Brkr4CmdClsAut_ADR 36
#define Brkr4CmdOpAut_ADR 37
#define Brkr4Closed_ADR 38
#define Brkr4Opened_ADR 39
#define Brkr4Local_ADR 40
#define Brkr4Auto_ADR 41
#define Brkr4Failure_ADR 42
#define Brkr5CmdClsAut_ADR 43
#define Brkr5CmdOpAut_ADR 44
#define Brkr5Closed_ADR 45
#define Brkr5Opened_ADR 46
#define Brkr5Local_ADR 47
#define Brkr5Auto_ADR 48
#define Brkr5Failure_ADR 49
#define Brkr6CmdClsAut_ADR 50
#define Brkr6CmdOpAut_ADR 51
#define Brkr6Closed_ADR 52
#define Brkr6Opened_ADR 53
#define Brkr6Local_ADR 54
#define Brkr6Auto_ADR 55
#define Brkr6Failure_ADR 56
#define Vlv1CmdClsAut_ADR 57
#define Vlv1CmdOpAut_ADR 58
#define Vlv1Closed_ADR 59
#define Vlv1Opened_ADR 60
#define Vlv1Local_ADR 61
#define Vlv1Auto_ADR 62
#define Vlv1Failure_ADR 63
#define Vlv2CmdClsAut_ADR 64
#define Vlv2CmdOpAut_ADR 65
#define Vlv2Closed_ADR 66
#define Vlv2Opened_ADR 67
#define Vlv2Local_ADR 68
#define Vlv2Auto_ADR 69
#define Vlv2Failure_ADR 70
#define Pmp2Failure_ADR 71
#define Pmp2Pressure_ADR 6
#define Pmp2CmdStpAut_ADR 72
#define Pmp2CmdStrtAut_ADR 73
#define Pmp2Running_ADR 74
#define Pmp2Stopped_ADR 75
#define Pmp2Local_ADR 76
#define Pmp2Auto_ADR 77
#define Pmp1Failure_ADR 78
#define Pmp1Pressure_ADR 7
#define Pmp1CmdStpAut_ADR 79
#define Pmp1CmdStrtAut_ADR 80
#define Pmp1Running_ADR 81
#define Pmp1Stopped_ADR 82
#define Pmp1Local_ADR 83
#define Pmp1Auto_ADR 84
#define Pmp1SpeedRef_ADR 8
#define Pmp1SpeedAct_ADR 9
#define VmsPressRef_ADR 10
#define VmsPressAct_ADR 11
#define Dmp1OpLim_ADR 85
#define Dmp1ClLim_ADR 86
#define Dmp1CmdOpAut_ADR 87
#define Dmp2OpLim_ADR 88
#define Dmp2ClLim_ADR 89
#define Dmp2CmdOpAut_ADR 90
#define FanCmdStartAut_ADR 91
#define FanCmdStopAut_ADR 92
#define FanLocal_ADR 93
#define FanAuto_ADR 94
#define FanFailure_ADR 95
#define FanRunning_ADR 96
#define FanPosRef_ADR 12
#define FanPosAct_ADR 13
#define Vlv3CmdClsAut_ADR 97
#define Vlv3CmdOpAut_ADR 98
#define Vlv3Closed_ADR 99
#define Vlv3Opened_ADR 100
#define Vlv3Local_ADR 101
#define Vlv3Auto_ADR 102
#define Vlv3Failure_ADR 103
#define Vlv3PosRef_ADR 14
#define Vlv3PosAct_ADR 15
#define SnsrPressRef_ADR 16
#define SnsrPressAct_ADR 17
#define SnsrTempRef_ADR 18
#define SnsrTempAct_ADR 19
#define AzpdRefSpeed_ADR 20
#define AzpdRefAngSTBD_ADR 21
#define AzpdRefAngPORT_ADR 22
#define AzpdActSpeed_ADR 23
#define AzpdActAngSTBD_ADR 24
#define AzpdActAngPORT_ADR 25
#define BtrRefSpSTBD_ADR 26
#define BtrRefSpPORT_ADR 27
#define BtaActSpSTBD_ADR 28
#define BtaActSpPORT_ADR 29
#define EsdActive_ADR 104
#define FireAlarmActive_ADR 105
